name: Build a Docker image and Push it to ACR v2
on:
  push:
    branches:
      - main

jobs:
  build-and-push-to-acr:
    name: Build And Push Docker Image To ACR
    uses: SumerSports/workflows/.github/workflows/build-and-push-to-acr.yaml@main
    secrets: inherit
#    with:
#      SERVICE_NAME: ""
#      TEST_DOCKER: false
