name: Build a Docker image and Push it to ACR v2
on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      service_name:
        description: |
          service name of the thing that's being built, this is also being used to tag the image
        required: true
        type: string
      dockerfile:
        default: "./Dockerfile"
        description: Dockerfile to use for the build
        required: false
        type: string
      publish:
        default: false
        description: 'Indicates whether to run Docker publish after build'
        required: false
        type: boolean

jobs:
  add-version-tag
      - name: Bump version and push tag
        if: ${{ inputs.push_to_nuget }}
        id: tag_version
        uses: mathieudutour/github-tag-action@v6.2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          tag_prefix: '${{ inputs.service_name }}-v'
  build-and-push-to-acr:
    name: Build And Push Docker Image To ACR
    uses: SumerSports/workflows/.github/workflows/build-and-push-to-ecr.yaml@main
    secrets: inherit
    with:
      # service name is used to tag the image, so it must conform to OCI registry tagging rules
      service_name: ""
      # the path to the dockerfile to use
      dockerfile: "./Dockerfile"
      # set to true if you need to run docker publish
      publish: false
