name: Build a Docker image and Push it to ECR
on:
  push:
    paths:
      # example paths
      - "dotnet/**"
      - ".github/workflows/build-and-push-to-ecr.yaml"
  workflow_dispatch:

jobs:
#  This is an example of a pre job you can run to get an example Dockerfile from the base images repo
# get-dockerfile:
#   name: Get Dockerfile
#   runs-on: ubuntu-latest
#   steps:
#     - name: Checkout Base Images
#       uses: actions/checkout@v4
#       with:
#         repository: SumerSports/base-images
#         path: base-images
#         ref: main
#         token: ${{ secrets.GH_SUMERDEVOPS_TOKEN }}

  build-and-push-default-image-to-ecr:
    name: Build And Push Default Docker Image To ECR
    uses: SumerSports/workflows/.github/workflows/build-and-push-to-ecr.yaml@main
    secrets: inherit
    with:
      # additional tags to add to this image, must include full registry and repo address and tag. Must be carriage
      # return delimited
      # exmple:
      # additional_tags: |
      #  <ECR Registry>/<ECR REPOSITORY NAME>:<TAG NAME>
      #  567639518918.dkr.ecr.us-east-1.amazonaws.com/base-images/dotnet-7:<NEW TAG>
      #  567639518918.dkr.ecr.us-east-1.amazonaws.com/base-images/dotnet-7:<ANOTHER TAG>
      # default:
      # additional_tags: ""
      #
      # path to Dockerfile the default is "./Dockerfile" this likely will not work,
      # so define your own. if you use the Get Dockerfile job above, you can
      # set the path like this example:
      # dockerfile: "./base-images/dotnet-7.0/example.dockerfile"
      # default:
      # dockerfile: ".Dockerfile"
      #
      # additional build args to pass to docker. Must be carriage return delimited
      # an example implementation of a dotnet build arg would look like:
      # build_args: |
      #   SOLUTION_FOLDER=<path to solution folder>
      #   PROJECT_NAME=<name of dotnet project>
      #   DD_GIT_REPOSITORY_URL=<url to git repo>
      #   DD_GIT_COMMIT_SHA=${{ github.sha }}
      #   RUN_TESTS=true
      # default:
      # build_args: ""
      #
      # name of the repo to push to ex: "base-images/dotnet-7" Required
      repo_name: ""
      #
      # Location for the aws registry
      # region: us-east-1
      #
      # AWS role to assume arn:aws:iam::${ACCOUNT}:role/<THIS ROLE NAME> Required
      role_name: ""
      #
      # Prefix for the semantic version tag to be pushed. Example "dotnet7-v" Required
      tag_prefix: ""
      #
      # Indicates whether to run Docker publish after build (you might want to only run a test, for example)
      # publish: false
