name: Scan For Deprecated K8s APIs
on:
  push:
    branches:
      - main
    paths:
      - "path/to/charts/**"
  workflow_dispatch:

jobs:
  scan-for-deprecated-k8s-apis:
    name: Scan For Deprecated K8s APIs
    uses: SumerSports/workflows/.github/workflows/scan-for-deprecated-k8s-apis.yaml@main
    secrets: inherit
    with:
      K8S_DIR: "path/to/charts/**"
