name: Scan For Deprecated K8s APIs
on:
  push:
    branches:
      - main

jobs:
  scan-for-deprecated-k8s-apis:
    name: Scan For Deprecated K8s APIs
    uses: SumerSports/workflows/.github/workflows/scan-for-deprecated-k8s-apis.yaml@main
    secrets: inherit
    
